title: <p align="center"> Gokula Krishnan R </p>
logo: /assets/img/gokul.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/gokul-krishnan-b6042b106/">LinkedIn</a> |
  <a href="https://github.com/GokulNov4">GitHub</a>
  <br>   
  I am a .Net full stack developer with 5 years of Experience.
  Currently learning ML & AI course to full fill my passion.
  <br>
  </p>

theme: jekyll-theme-minimal
